title: NFT Universe
description: The yellow-pages of the NFT labs
theme: just-the-docs

url: https://guidepaper.github.io

aux_links:
  Git Repo of the Lab: https://github.com/guidepaper/guidepaper.github.io
