title: Oracle
description: The yellow-pages of the NFT labs
theme: just-the-docs

url: https://guidepaper.github.io

aux_links:
  Template Repository: https://github.com/guidepaper/guidepaper.github.io
